### ISSUE TITLE
Machine Learning Assignment 1 

### ISSUE THREAD

**Issue by arslanaslam007** [arslanaslam007/7th-Semester#9]
Initiated On ->
Friday , 28 September 2018

Date of Submission ->
Friday , 05 October 2018

Click the Link to get it
https://drive.google.com/open?id=1cfcmLkjBdfofjZ610ZdT6quyOTeq_vrd

Click the Link to get the Solution
https://drive.google.com/open?id=1sFzurHOTQyF2x4zp20QUSVYizCVtSqVd

**Comment by OzairKhanBro** [comment]
any solution?

**Comment by msalmansaeedch786** [comment]
Solution Please?

**Comment by Mehakimtiaz** [comment]
solution???

**Comment by arslanaslam007** [comment]
Hold On......
we will work together to figure out solution...

**Comment by arslanaslam007** [comment]
**My Homework 1  Stat**

Linear Regression   f_1vsRemainingRest

1 degree PredictLR 63.3500
2 degree PredictLR 27.7500
3 degree PredictLR 12.8000

1 degree PredictLRPro 93.4500
2 degree PredictLRPro 88.2000
3 degree PredictLRPro 79.7000

Linear Regression f_1vsRest

1 degree predictLR 93.1000
2 degree PredictLR 54.0500

1 degree predictLRPro 44.90000
2 degree predictLRPro 19.7500
3 degree predictLRPro 6.5500

1 degree standardization 95.8500
1 degree standardization predictLRPro 96.2500

2 degree standardization 95.9000
2 degree standardization predictPro 97

Linear Regression  f_1vs1

1 degree PredictLR 18
2 degree PredictLR 2.8500
3 degree PredictLR 3.5000
